# Generated by Django 4.2.1 on 2023-06-21 10:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('idHouse', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(default='NOT SPECIFIED', max_length=150)),
                ('number', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=500)),
                ('space', models.CharField(max_length=20)),
                ('rooms', models.CharField(max_length=20)),
                ('bathrooms', models.CharField(max_length=20)),
                ('floor', models.CharField(max_length=10)),
                ('totFloor', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=5000)),
                ('parking', models.CharField(max_length=200)),
                ('contract', models.CharField(max_length=20)),
                ('typology', models.CharField(max_length=50)),
                ('energyClass', models.CharField(max_length=50)),
                ('energyHeating', models.CharField(max_length=50)),
                ('energyUnit', models.CharField(max_length=15)),
                ('urlUserProfile', models.CharField(max_length=1000)),
                ('nameUser', models.CharField(max_length=200)),
                ('otherCharacteristics', models.CharField(max_length=80)),
                ('condominiumExpenses', models.CharField(max_length=10)),
                ('caution', models.CharField(max_length=5)),
                ('statusApartment', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=1000)),
                ('refDataAnnuncio', models.CharField(max_length=30)),
                ('vetrina', models.BooleanField(default=False)),
                ('advertising', models.CharField(max_length=100)),
                ('dateAdded', models.DateField(default=datetime.date(2023, 6, 21))),
            ],
        ),
        migrations.CreateModel(
            name='MachineProcess',
            fields=[
                ('idStateMachine', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('PLAY', 'ACTIVE'), ('PAUSE', 'PAUSE'), ('STOP', 'STOP')], default='STOP', max_length=50)),
                ('startedDate', models.DateField(default=datetime.date(2023, 6, 21))),
                ('startedDateTime', models.TimeField(default=datetime.time(12, 53, 55, 407364))),
                ('finishDate', models.DateField(blank=True, null=True)),
                ('finishDateTIme', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeManager',
            fields=[
                ('idTimeManager', models.AutoField(primary_key=True, serialize=False)),
                ('workAgentState', models.CharField(max_length=20)),
                ('cycleAgent', models.CharField(max_length=20)),
                ('numberCycle', models.IntegerField()),
                ('addedDate', models.DateField(default=datetime.date(2023, 6, 21))),
                ('addedDateTime', models.TimeField(default=datetime.time(12, 53, 55, 406887))),
                ('updateDate', models.DateField(blank=True, null=True)),
                ('updateDateTime', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UrlTrackProcess',
            fields=[
                ('id_url_track_process', models.AutoField(primary_key=True, serialize=False)),
                ('url_page', models.CharField(max_length=300)),
                ('url_card', models.CharField(max_length=300)),
                ('dateStarted', models.DateField(default=datetime.datetime.now)),
                ('seconds_execution', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('minutes_execution', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackProcess',
            fields=[
                ('identifierProcess', models.AutoField(primary_key=True, serialize=False)),
                ('numPage', models.IntegerField(default=20)),
                ('numCard', models.IntegerField(default=33)),
                ('urlLastPage', models.CharField(max_length=250)),
                ('urlLastCard', models.CharField(max_length=250)),
                ('options', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('errorStack', models.CharField(default='NO ERROR', max_length=10000)),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.machineprocess')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('messageId', models.AutoField(primary_key=True, serialize=False)),
                ('dateSent', models.DateField(default=datetime.date(2023, 6, 21))),
                ('dateTimeSent', models.TimeField(default=datetime.time(12, 53, 55, 396188))),
                ('message', models.CharField(max_length=5000)),
                ('options', models.CharField(max_length=200)),
                ('house', models.ManyToManyField(to='api.house')),
            ],
        ),
        migrations.AddField(
            model_name='machineprocess',
            name='timeManager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.timemanager'),
        ),
    ]
