# Generated by Django 4.2.1 on 2023-06-20 14:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(default='NOT SPECIFIED', max_length=150)),
                ('number', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=500)),
                ('space', models.CharField(max_length=20)),
                ('rooms', models.CharField(max_length=20)),
                ('bathrooms', models.CharField(max_length=20)),
                ('floor', models.CharField(max_length=10)),
                ('totFloor', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=5000)),
                ('parking', models.CharField(max_length=200)),
                ('contract', models.CharField(max_length=20)),
                ('typology', models.CharField(max_length=50)),
                ('energyClass', models.CharField(max_length=50)),
                ('energyHeating', models.CharField(max_length=50)),
                ('energyUnit', models.CharField(max_length=15)),
                ('urlUserProfile', models.CharField(max_length=1000)),
                ('nameUser', models.CharField(max_length=200)),
                ('otherCharacteristics', models.CharField(max_length=80)),
                ('condominiumExpenses', models.CharField(max_length=10)),
                ('caution', models.CharField(max_length=5)),
                ('statusApartment', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=1000)),
                ('refDataAnnuncio', models.CharField(max_length=30)),
                ('vetrina', models.BooleanField(default=False)),
                ('advertising', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MachineProcess',
            fields=[
                ('idStateMachine', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('PLAY', 'ACTIVE'), ('PAUSE', 'PAUSE'), ('STOP', 'STOP')], default='STOP', max_length=50)),
                ('startedDate', models.DateTimeField(default=datetime.datetime.now)),
                ('startedDateTime', models.TimeField(default=datetime.datetime.now)),
                ('finishDate', models.DateTimeField(default=datetime.datetime.now)),
                ('finishDateTIme', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UrlTrackProcess',
            fields=[
                ('id_url_track_process', models.AutoField(primary_key=True, serialize=False)),
                ('url_page', models.CharField(max_length=300)),
                ('url_card', models.CharField(max_length=300)),
                ('dateStarted', models.DateTimeField(default=datetime.datetime.now)),
                ('seconds_execution', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('minutes_execution', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackProcess',
            fields=[
                ('identifierProcess', models.AutoField(primary_key=True, serialize=False)),
                ('numPage', models.IntegerField(default=20)),
                ('numCard', models.IntegerField(default=33)),
                ('urlLastPage', models.IntegerField(max_length=200)),
                ('urlLastCard', models.IntegerField(max_length=200)),
                ('options', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('errorStack', models.CharField(default='NO ERROR', max_length=10000)),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.machineprocess')),
            ],
        ),
        migrations.CreateModel(
            name='TimeManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageName', models.CharField(max_length=100)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=5000)),
                ('numberSent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.house')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageName', models.CharField(max_length=100)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=5000)),
                ('numberSent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.house')),
            ],
        ),
    ]
