# Generated by Django 4.1.2 on 2022-10-24 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=500)),
                ('space', models.CharField(max_length=20)),
                ('rooms', models.CharField(max_length=20)),
                ('floor', models.CharField(max_length=20)),
                ('bathrooms', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=5000)),
                ('title', models.CharField(max_length=100)),
                ('parking', models.CharField(max_length=20)),
                ('energyClass', models.CharField(max_length=20)),
                ('energyHeating', models.CharField(max_length=20)),
                ('urlUserProfile', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=1000)),
                ('number', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageName', models.CharField(max_length=100)),
                ('dateAdded', models.DateField(auto_now_add=True)),
                ('message', models.CharField(max_length=5000)),
                ('numberSent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.house')),
            ],
        ),
    ]
