# Generated by Django 4.2.1 on 2023-06-21 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.date(2023, 6, 21)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='finishDate',
            field=models.DateTimeField(default=datetime.date(2023, 6, 21)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='finishDateTIme',
            field=models.TimeField(default=datetime.time(11, 22, 10, 500799)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDate',
            field=models.DateTimeField(default=datetime.date(2023, 6, 21)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDateTime',
            field=models.TimeField(default=datetime.time(11, 22, 10, 500769)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateSent',
            field=models.DateTimeField(default=datetime.date(2023, 6, 21)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateTimeSent',
            field=models.TimeField(default=datetime.time(11, 22, 10, 499727)),
        ),
        migrations.AlterField(
            model_name='urltrackprocess',
            name='dateStarted',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 9, 22, 10, 501416, tzinfo=datetime.timezone.utc)),
        ),
    ]
