# Generated by Django 4.2.1 on 2023-07-03 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowInputScraperConfig',
            fields=[
                ('id_flow_input_scraper_config', models.AutoField(primary_key=True, serialize=False)),
                ('totNumPage', models.CharField(max_length=4)),
                ('totNumCards', models.CharField(max_length=4)),
                ('contract', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('refreshSearch', models.JSONField()),
                ('message', models.BooleanField()),
                ('messageWebSite', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='house',
            name='dateAdded',
            field=models.DateField(default=datetime.date(2023, 7, 3)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDate',
            field=models.DateField(default=datetime.date(2023, 7, 3)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDateTime',
            field=models.TimeField(default=datetime.time(19, 3, 48, 822194)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateSent',
            field=models.DateField(default=datetime.date(2023, 7, 3)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateTimeSent',
            field=models.TimeField(default=datetime.time(19, 3, 48, 809676)),
        ),
        migrations.AlterField(
            model_name='timemanager',
            name='addedDate',
            field=models.DateField(default=datetime.date(2023, 7, 3)),
        ),
        migrations.AlterField(
            model_name='timemanager',
            name='addedDateTime',
            field=models.TimeField(default=datetime.time(19, 3, 48, 821668)),
        ),
    ]
