# Generated by Django 4.1.2 on 2022-11-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_house_advertising_house_vetrina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='parking',
            field=models.CharField(max_length=200),
        ),
    ]
