# Generated by Django 4.2.1 on 2023-06-21 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_house_dateadded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='finishDate',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='finishDateTIme',
            field=models.TimeField(default=datetime.time(11, 27, 18, 238267)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDate',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDateTime',
            field=models.TimeField(default=datetime.time(11, 27, 18, 238238)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateSent',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateTimeSent',
            field=models.TimeField(default=datetime.time(11, 27, 18, 227691)),
        ),
        migrations.AlterField(
            model_name='urltrackprocess',
            name='dateStarted',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 9, 27, 18, 238890, tzinfo=datetime.timezone.utc)),
        ),
    ]
