# Generated by Django 4.2.1 on 2023-07-05 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_flowinputscraperconfig_alter_house_dateadded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='dateTimeAdded',
            field=models.TimeField(default=datetime.time(17, 43, 32, 534466)),
        ),
        migrations.AlterField(
            model_name='house',
            name='dateAdded',
            field=models.DateField(default=datetime.date(2023, 7, 5)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDate',
            field=models.DateField(default=datetime.date(2023, 7, 5)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDateTime',
            field=models.TimeField(default=datetime.time(17, 43, 32, 559671)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateSent',
            field=models.DateField(default=datetime.date(2023, 7, 5)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateTimeSent',
            field=models.TimeField(default=datetime.time(17, 43, 32, 558159)),
        ),
        migrations.AlterField(
            model_name='timemanager',
            name='addedDate',
            field=models.DateField(default=datetime.date(2023, 7, 5)),
        ),
        migrations.AlterField(
            model_name='timemanager',
            name='addedDateTime',
            field=models.TimeField(default=datetime.time(17, 43, 32, 559105)),
        ),
    ]
