# Generated by Django 4.2.1 on 2023-06-21 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_house_dateadded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.date(2023, 6, 21)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='finishDate',
            field=models.DateTimeField(default=datetime.date(2023, 6, 21)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='finishDateTIme',
            field=models.TimeField(default=datetime.time(11, 30, 31, 160081)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDate',
            field=models.DateTimeField(default=datetime.date(2023, 6, 21)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDateTime',
            field=models.TimeField(default=datetime.time(11, 30, 31, 160052)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateSent',
            field=models.DateTimeField(default=datetime.date(2023, 6, 21)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateTimeSent',
            field=models.TimeField(default=datetime.time(11, 30, 31, 149141)),
        ),
        migrations.AlterField(
            model_name='urltrackprocess',
            name='dateStarted',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 9, 30, 31, 160735, tzinfo=datetime.timezone.utc)),
        ),
    ]
