# Generated by Django 4.2.1 on 2023-09-08 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_urltrackprocess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='caution',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='condominiumExpenses',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='dateAdded',
            field=models.DateField(default=datetime.date(2023, 9, 8)),
        ),
        migrations.AlterField(
            model_name='house',
            name='dateTimeAdded',
            field=models.TimeField(default=datetime.time(17, 55, 54, 385408)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDate',
            field=models.DateField(default=datetime.date(2023, 9, 8)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDateTime',
            field=models.TimeField(default=datetime.time(17, 55, 54, 399968)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateSent',
            field=models.DateField(default=datetime.date(2023, 9, 8)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateTimeSent',
            field=models.TimeField(default=datetime.time(17, 55, 54, 398427)),
        ),
        migrations.AlterField(
            model_name='timemanager',
            name='addedDate',
            field=models.DateField(default=datetime.date(2023, 9, 8)),
        ),
        migrations.AlterField(
            model_name='timemanager',
            name='addedDateTime',
            field=models.TimeField(default=datetime.time(17, 55, 54, 399352)),
        ),
    ]
