# Generated by Django 4.2.1 on 2023-06-21 09:33

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_house_dateadded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='dateAdded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='finishDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='finishDateTIme',
            field=models.TimeField(default=datetime.time(11, 33, 12, 344175)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDateTime',
            field=models.TimeField(default=datetime.time(11, 33, 12, 344145)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateSent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateTimeSent',
            field=models.TimeField(default=datetime.time(11, 33, 12, 332829)),
        ),
        migrations.AlterField(
            model_name='urltrackprocess',
            name='dateStarted',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 9, 33, 12, 344826, tzinfo=datetime.timezone.utc)),
        ),
    ]
