# Generated by Django 4.2.1 on 2023-06-21 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_house_dateadded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineprocess',
            name='finishDate',
            field=models.DateTimeField(default=datetime.date(2023, 6, 21)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='finishDateTIme',
            field=models.TimeField(default=datetime.time(11, 38, 8, 342604)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDate',
            field=models.DateTimeField(default=datetime.date(2023, 6, 21)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDateTime',
            field=models.TimeField(default=datetime.time(11, 38, 8, 342574)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateTimeSent',
            field=models.TimeField(default=datetime.time(11, 38, 8, 332156)),
        ),
        migrations.AlterField(
            model_name='urltrackprocess',
            name='dateStarted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
