# Generated by Django 4.2.1 on 2023-09-12 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_house_caution_alter_house_condominiumexpenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='caution',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='house',
            name='condominiumExpenses',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='house',
            name='dateAdded',
            field=models.DateField(default=datetime.date(2023, 9, 12)),
        ),
        migrations.AlterField(
            model_name='house',
            name='dateTimeAdded',
            field=models.TimeField(default=datetime.time(22, 19, 57, 624005)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDate',
            field=models.DateField(default=datetime.date(2023, 9, 12)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDateTime',
            field=models.TimeField(default=datetime.time(22, 19, 57, 636245)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateSent',
            field=models.DateField(default=datetime.date(2023, 9, 12)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateTimeSent',
            field=models.TimeField(default=datetime.time(22, 19, 57, 634962)),
        ),
        migrations.AlterField(
            model_name='timemanager',
            name='addedDate',
            field=models.DateField(default=datetime.date(2023, 9, 12)),
        ),
        migrations.AlterField(
            model_name='timemanager',
            name='addedDateTime',
            field=models.TimeField(default=datetime.time(22, 19, 57, 635740)),
        ),
    ]
