# Generated by Django 4.2.1 on 2023-06-21 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_machineprocess_finishdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineprocess',
            name='finishDate',
            field=models.DateField(default=datetime.date(2023, 6, 21)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='finishDateTIme',
            field=models.TimeField(default=datetime.time(11, 39, 36, 349034)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDate',
            field=models.DateField(default=datetime.date(2023, 6, 21)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDateTime',
            field=models.TimeField(default=datetime.time(11, 39, 36, 349005)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateTimeSent',
            field=models.TimeField(default=datetime.time(11, 39, 36, 337849)),
        ),
        migrations.AlterField(
            model_name='urltrackprocess',
            name='dateStarted',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
