# Generated by Django 4.2.1 on 2023-06-21 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_machineprocess_finishdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='dateAdded',
            field=models.DateField(default=datetime.date(2023, 6, 21)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='finishDateTIme',
            field=models.TimeField(default=datetime.time(11, 41, 35, 534077)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDateTime',
            field=models.TimeField(default=datetime.time(11, 41, 35, 534048)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateSent',
            field=models.DateField(default=datetime.date(2023, 6, 21)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateTimeSent',
            field=models.TimeField(default=datetime.time(11, 41, 35, 523046)),
        ),
    ]
