# Generated by Django 4.2.1 on 2023-06-21 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_house_dateadded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineprocess',
            name='finishDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='finishDateTIme',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDateTime',
            field=models.TimeField(default=datetime.time(11, 43, 10, 789390)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateTimeSent',
            field=models.TimeField(default=datetime.time(11, 43, 10, 778323)),
        ),
    ]
