# Generated by Django 4.2.1 on 2023-06-21 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_machineprocess_finishdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineprocess',
            name='finishDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='finishDateTIme',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDateTime',
            field=models.TimeField(default=datetime.time(11, 45, 0, 108004)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateTimeSent',
            field=models.TimeField(default=datetime.time(11, 45, 0, 96252)),
        ),
    ]
