# Generated by Django 4.2.1 on 2023-06-21 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_machineprocess_finishdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDateTime',
            field=models.TimeField(default=datetime.time(11, 45, 38, 166992)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateTimeSent',
            field=models.TimeField(default=datetime.time(11, 45, 38, 155615)),
        ),
        migrations.AlterField(
            model_name='trackprocess',
            name='urlLastCard',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='trackprocess',
            name='urlLastPage',
            field=models.CharField(max_length=250),
        ),
    ]
