# Generated by Django 4.2.1 on 2023-10-06 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_house_datetimeadded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='dateAdded',
            field=models.DateField(default=datetime.date(2023, 10, 6)),
        ),
        migrations.AlterField(
            model_name='house',
            name='dateTimeAdded',
            field=models.TimeField(default=datetime.time(22, 10, 26, 405305)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDate',
            field=models.DateField(default=datetime.date(2023, 10, 6)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDateTime',
            field=models.TimeField(default=datetime.time(22, 10, 26, 428670)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateSent',
            field=models.DateField(default=datetime.date(2023, 10, 6)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateTimeSent',
            field=models.TimeField(default=datetime.time(22, 10, 26, 427331)),
        ),
        migrations.AlterField(
            model_name='timemanager',
            name='addedDate',
            field=models.DateField(default=datetime.date(2023, 10, 6)),
        ),
        migrations.AlterField(
            model_name='timemanager',
            name='addedDateTime',
            field=models.TimeField(default=datetime.time(22, 10, 26, 428168)),
        ),
    ]
