# Generated by Django 4.2.1 on 2023-10-06 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_house_datetimeadded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='dateTimeAdded',
            field=models.TimeField(default=datetime.time(22, 18, 35, 815399)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDateTime',
            field=models.TimeField(default=datetime.time(22, 18, 35, 833352)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateTimeSent',
            field=models.TimeField(default=datetime.time(22, 18, 35, 832135)),
        ),
        migrations.AlterField(
            model_name='timemanager',
            name='addedDateTime',
            field=models.TimeField(default=datetime.time(22, 18, 35, 832883)),
        ),
    ]
