# Generated by Django 4.2.1 on 2023-10-07 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_house_datetimeadded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='dateAdded',
            field=models.DateField(default=datetime.date(2023, 10, 7)),
        ),
        migrations.AlterField(
            model_name='house',
            name='dateTimeAdded',
            field=models.TimeField(default=datetime.time(21, 53, 42, 331606)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDate',
            field=models.DateField(default=datetime.date(2023, 10, 7)),
        ),
        migrations.AlterField(
            model_name='machineprocess',
            name='startedDateTime',
            field=models.TimeField(default=datetime.time(21, 53, 42, 355615)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateSent',
            field=models.DateField(default=datetime.date(2023, 10, 7)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateTimeSent',
            field=models.TimeField(default=datetime.time(21, 53, 42, 354097)),
        ),
        migrations.AlterField(
            model_name='timemanager',
            name='addedDate',
            field=models.DateField(default=datetime.date(2023, 10, 7)),
        ),
        migrations.AlterField(
            model_name='timemanager',
            name='addedDateTime',
            field=models.TimeField(default=datetime.time(21, 53, 42, 355066)),
        ),
    ]
